from datetime import datetime

def generate_report(result):

    disease = result["prediction"]
    confidence = result["confidence"] * 100

    report = f"""
# AI Medical Report

Date:
{datetime.now().strftime('%d-%m-%Y %H:%M')}

Prediction:
{disease}

Confidence:
{confidence:.2f}%

Clinical Summary:
The uploaded skin lesion image is most consistent with **{disease}**.

Recommendation:
• Consult a dermatologist.
• Perform dermoscopic examination if necessary.
• Continue regular skin monitoring.
• Seek immediate medical attention if the lesion changes rapidly.

Disclaimer:
This prediction is generated by an AI model and should not replace professional medical diagnosis.
"""

    return report